### ISSUE TITLE
Not able to run without profiling master branch

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#322]
**Describe the bug**
Master branch can only run with profiling enabled.

**To Reproduce**
1. Checkout and pull latest master branch
2. poetry run baler --project public_datasets hurricane_transformed --mode train

**Expected behavior**
After training completes you are presented with the following error:

```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pekman/baler/baler/baler.py", line 66, in main
    check_enabled_profilers(
  File "/home/pekman/baler/baler/baler.py", line 125, in check_enabled_profilers
    return outer_function(lambda: inner_function(f, *args, **kwargs))()
TypeError: 'NoneType' object is not callabl
```

**System Information**
Ubuntu 20.04

**Comment by exook** [comment]
@AkkiG2401 Can you have a look at this ASAP?

**Comment by fritjof-b** [comment]
A quickfix would be to explicitly add a check to the return value for the following snippet in `baler.py`

```python3
def check_enabled_profilers(
    f, pytorchProfile=False, energyProfile=False, *args, **kwargs
):
    """
    Conditionally apply profiling based on the given boolean flags.

    Args:
        f (callable): The function to be potentially profiled.
        pytorchProfile (bool): Whether to apply PyTorch profiling.
        energyProfile (bool): Whether to apply energy profiling.

    Returns:
        result: The result of the function `f` execution.
    """

    # Placeholder function to avoid nested conditions
    def identity_func(fn, *a, **kw):
        return fn(*a, **kw)

    # Set the outer and inner functions based on the flags
    inner_function = pytorch_profile if pytorchProfile else identity_func
    outer_function = (
        (
            lambda fn: energy_profiling(
                fn, project_name="baler_training", measure_power_secs=1
            )
        )
        if energyProfile
        else identity_func
    )

    # Nest the profiling steps and run the function only once
    return outer_function(lambda: inner_function(f, *args, **kwargs))()
    ```
