### ISSUE TITLE
Docker path issue with new directory structure

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#43]
The new directory structure works great running locally using only poetry. Running with a newly built docker image however gives a path issue. Follow the README on the `newDirStructure` branch to replicate

Poetry works (train, compress, decompress, plot, info):
`poetry run python baler --project=firstProject --mode=train`

Docker gets a path related issue:
`docker run --mount type=bind,source=${PWD}/projects/,target=/projects baler:latest --project=firstProject --mode=train`

Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/baler-root/baler/__main__.py", line 2, in <module>
    baler.main()
  File "/baler-root/baler/baler.py", line 13, in main
    config, mode, project = helper.get_arguments()
  File "/baler-root/baler/modules/helper.py", line 35, in get_arguments
    args.config= data_processing.import_config(config_path)
  File "/baler-root/baler/modules/data_processing.py", line 17, in import_config
    with open (config_path) as json_config:
FileNotFoundError: [Errno 2] No such file or directory: './projects/firstProject/config.json'
```

**Comment by OliverWoolland** [comment]
Resolved by changing README, will be further resolved by refactoring in #111
